# html lang
# ---------------
language:

# Main menu navigation
# ---------------
menu:
  主页: /
  文章总览: /archives
  关于我们: /about
  分类: /categories
  标签: /tags
  个人相册: /gallery


  # Tags: /tags
  # Categories: /categories
  #XXX: /xxx

# Favicon
# ---------------
favicon: /favicon.ico

# PWA
# ---------------
pwa:
  enable: false
  manifest:


# Highlight theme
# ---------------
highlight_theme: default

# Nav settings
# ---------------
social:
  #icon_name: url
  telegram: https://mail.qq.com/cgi-bin/qm_share?t=qm_mailme&email=908934816@qq.com
  rss: /atom.xml


# Algolia search
# ---------------
algolia_search:
  enable: false
  hits:
    per_page: 10
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}"
    hits_stats: "${hits} results found in ${time} ms"

# Local search
# ---------------
local_search:
  enable: true
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}"

# MathJax
# ---------------
mathjax:
  enable: false
  cdn: https://cdn.bootcss.com/mathjax/2.7.2/MathJax.js?config=TeX-AMS-MML_HTMLorMML


# Toggle fireworks (IE >= 10)
# ---------------
fireworks: true

# Analysis
# ---------------
baidu_analytics: 3f2224e84fb41c8beaba0224b5142794

google_analytics: UA-121920923-2

# stylesheets loaded in the <head>
# ---------------
stylesheets:
- /css/index.css

# scripts loaded in the end of the body
# ---------------
scripts:
- /js/utils.js
- /js/fancybox.js
- /js/sidebar.js
- /js/copy.js
- /js/fireworks.js
- /js/transition.js
- /js/scroll.js
- /js/head.js

# cdn for third-party library
# ---------------
cdn:
  css:
    fontawesome: https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.min.css
  js:
    anime: /js/third-party/anime.min.js
    jquery: /js/third-party/jquery.min.js
    fancybox: /js/third-party/jquery.fancybox.min.js
    velocity: /js/third-party/velocity.min.js
    velocity-ui: /js/third-party/velocity.ui.min.js

# Post info settings
# ---------------
avatar: http://blog.fueson.top/avatar/me.jpg?imageMogr2/thumbnail/200x200>/gravity/Center/crop/200x200/format/jpg/blur/1x0/quality/75|imageslim

top_img: http://blog.fueson.top/bg/saber.jpg

post_meta:
  date_type: created # created or updated
  categories: true
  tags: true

wordcount:
  enable: true

toc:
  enable: true

heart:
  enable: true
  href: https://www.jucaizhan.com/
  text: 感谢访问本站 ^_^

post_copyright:
  enable: true
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

auto_excerpt:
   enable: true
   length: 150

# slide
# For reveal.js config, see https://github.com/hakimel/reveal.js#configuration
slide:
  separator: ---
  separator_vertical: --
  charset: utf-8
  theme: black
  # optional
  mouseWheel: false
  transition: slide
  transitionSpeed: default
  parallaxBackgroundImage: ''
  parallaxBackgroundSize: ''
  parallaxBackgroundHorizontal: null
  parallaxBackgroundVertical: null

# QR_code:
  # - itemlist:
  #     img:
  #     text:

# adv:
  # enable: false
  # info:

# Share System
# ---------------
addThis:
  enable: false
  #pubid:

# sharejs:
  # enable: false
  # disabled_sites:

# Comments System
# ---------------
disqus:
  enable: false
  shortname: fridolph
  count: true

# laibili:
  # enable: false
  # uid:

# gitment
  # enable: false
  # owner:
  # repo:
  # client_id:
  # client_secret:

gitalk:
   enable: true
   client_id: 58c55a7244de19e196b7
   client_secret: 36193ea6255115da581cda3f178fa9dcccfe7873
   repo: blog
   owner: longbaobao
   admin: longbaobao
   distractionFreeMode: true

# valine comment system. https://valine.js.org
# valine:
#   enable: false # if you want use valine,please set this value is ture
#   appId:  # leancloud application app id
#   appKey:  # leancloud application app key
#   notify: false # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
#   verify: false # valine verify code (true/false)
#   pageSize: 10 # comment list page size
#   avatar: mm # gravatar style https://valine.js.org/#/avatar
#   lang: zh-cn # i18n: zh-cn/en
#   placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
#   guest_info: nick,mail,link #valine comment header inf

# Footer Settings
# ---------------
since: 2018

ICP:
  enable: true
  text: 冀ICP备16022574号-1

# busuanzi count for PV / UV in site
busuanzi:
  # count values only if the other configs are false
  enable: true
  # custom uv span for the whole site
  site_uv: true
  site_uv_header: <i class="fa fa-user"></i>
  site_uv_footer:
  # custom pv span for the whole site
  site_pv: true
  site_pv_header: <i class="fa fa-eye"></i>
  site_pv_footer:
  # custom pv span for one page only
  page_pv: true
  page_pv_header: <i class="fa fa-file-o"></i>
  page_pv_footer:


# Sidebar Settings
# ---------------
#links_title: Links
#links:
  #Name: url

meiqia:
   enable: true
